FROM golang:latest

WORKDIR /chess

COPY . .

RUN go mod download

RUN go run github.com/prisma/prisma-client-go generate

RUN go install github.com/cosmtrek/air@latest

EXPOSE 8000

CMD go run github.com/prisma/prisma-client-go migrate deploy; air