version: '3'

services:
  traefik-dev:
    image: traefik:v2.9
    container_name: traefik_chess_dev_container
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/:/etc/traefik/:ro
    networks:
      - chess-dev-traefik-net

  web-dev:
    container_name: web_chess_dev_container
    environment: 
      - NEXT_PUBLIC_API_ADDRESS=https://api.chess.localhost
    build: 
      context: ./web
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./web:/web
      - /web/node_modules/
    restart: on-failure
    labels:
      - traefik.enable=true
      - traefik.http.routers.web-dev.rule=Host(`client.chess.localhost`)
      - traefik.http.routers.web-dev.tls=true
    networks:
      chess-dev-traefik-net:
        aliases:
          - client.chess.localhost

  api-dev:
    container_name: api_chess_dev_container
    environment:
      - LISTEN_ADDR=:80
      - LOG_LEVEL=${LOG_LEVEL}
      - DATABASE_URL=postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@postgresdb-dev:5432/${DATABASE_NAME}
      - PRODUCTION=true
      - PUBLIC_WEB_ADDRESS=https://client.chess.localhost
      - HASH_KEY=${HASH_KEY}
      - BLOCK_KEY=${BLOCK_KEY}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
    tty: true
    build: 
      context: ./
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./:/chess
      - /chess/web/
    restart: on-failure
    depends_on:
      - postgresdb-dev
    labels:
      - traefik.enable=true
      - traefik.http.routers.api-dev.rule=Host(`api.chess.localhost`)
      - traefik.http.routers.api-dev.tls=true
    networks:
      chess-dev-postgres-net:
      chess-dev-traefik-net:
        aliases:
          - api.chess.localhost

  postgresdb-dev:
    image: postgres:latest
    container_name: postgres_chess_dev_container
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    networks:
      - chess-dev-postgres-net

networks:
  chess-dev-postgres-net:
    driver: bridge
  chess-dev-traefik-net:
    external: true
