http:
  routers:
    traefik:
      rule: "Host(`traefik.chess.localhost`)"
      service: "api@internal"
      tls:
        domains:
          - main: "chess.localhost"
            sans:
              - "*.chess.localhost"

tls:
  certificates:
    - certFile: "/etc/traefik/certs/local-cert.pem"
      keyFile: "/etc/traefik/certs/local-key.pem"
